# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 SmoothTeam
#
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

[package]
name = "upac-setup"
description = "First-boot bootstrap installer: initial disk layout for a blank system"
version.workspace = true

edition.workspace = true
rust-version.workspace = true

license.workspace = true

readme.workspace = true
homepage.workspace = true
repository.workspace = true

keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
upac-lib   = { workspace = true, features = ["builtin-all-booters", "builtin-all-decoders"] }
upac-types = { workspace = true }
upac-abi   = { workspace = true }
upac-macro = { workspace = true }

composefs  = { workspace = true }
nix        = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
sha2       = { workspace = true }
toml       = { workspace = true }
uuid       = { workspace = true }
tar        = { workspace = true }
flate2     = { workspace = true }
xz2        = { workspace = true }
zstd       = { workspace = true }
tempfile   = { workspace = true }

sevenz-rust2 = "0.22.2"
btrfs-mkfs = "0.13.0"
gptman     = "3.1.1"
fatfs      = "0.3"
zip = "8.6.0"

[build-dependencies]
toml = { workspace = true }
